# Generated by Django 4.0.4 on 2022-05-22 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
                ('imagen', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Pyme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=500)),
                ('sitio_web', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Restriccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField()),
                ('descripcion', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='edad',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='suscripcion',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='Usuario_Restriccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restriccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.restriccion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Propaganda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=10)),
                ('pyme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pyme')),
            ],
        ),
    ]
